# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


# password

#http://localhost:8080/oauth/authorize?client_id=client&redirect_uri=http://localhost:9000/callback&response_type=code&scope=read_profile
#http://localhost:8080/oauth/authorize?client_id=client&redirect_uri=http://localhost:9000/callback&response_type=token&scope=read_profile&state=test


# Authorization Code Grant Type 토큰 요청
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50OnBhc3N3b3Jk

code=lg8HLw&grant_type=authorization_code&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fcallback&scope=read_profile
###

# Password Grant Type 토큰 요청
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50OnBhc3N3b3Jk

username=user&password=pass&grant_type=password&scope=read_profile
###

# Client Credentials Grant Type 방식
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50OnBhc3N3b3Jk

grant_type=client_credentials&scope=read_profile
###

# Refresh Token Type
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50OnBhc3N3b3Jk

grant_type=refresh_token&scope=read_profile&refresh_token=2ec7cfcc-110b-42a0-859f-fc72b6067935
###


# session 조회
GET http://localhost:8080/api/session
Accept: application/json
Authorization: Bearer 9298f76f-c10c-4802-ba60-6c49d3e715f3

###